server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8081/eureka/

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    order-service:
      path: /order/**
      serviceId: order-service
      retryable: false
      stripPrefix: false
    product-service:
      path: /product/**
      serviceId: product-service
      retryable: false
      stripPrefix: false
    customer-service:
      path: /customer/**
      serviceId: customer-service
      retryable: false
      stripPrefix: false